# These are supported funding model platforms

patreon: JasminDreasond
open_collective: JasminDreasond
ko_fi: JasminDreasond
custom: ['https://ud.me/jasmindreasond.wallet', 'https://doh.pw/?d=bitcoin:bc1qnk7upe44xrsll2tjhy5msg32zpnqxvyysyje2g']
